runtime: python311  # or python310, python39, etc.

entrypoint: gunicorn -b :$PORT main:app

instance_class: F1  # Optional: Set machine class (F1 is smallest, F2 has more resources)

env_variables:
  FLASK_ENV: production  # Example environment variable

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
- url: /.*
  script: auto
